In [57]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import numpy as np
from sklearn.linear_model import LinearRegression, ElasticNet
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, mean_squared_error, mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
#import required libs

In [107]:
#reading dfs
df = pd.read_csv('train.csv', sep=',')
df

,id,Brand,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg),Price
0,0,Jansport,Leather,Medium,7.0,Yes,No,Tote,Black,11.611723,112.15875
1,1,Jansport,Canvas,Small,10.0,Yes,Yes,Messenger,Green,27.078537,68.88056
2,2,Under Armour,Leather,Small,2.0,Yes,No,Messenger,Red,16.643760,39.17320
3,3,Nike,Nylon,Small,8.0,Yes,No,Messenger,Green,12.937220,80.60793
4,4,Adidas,Canvas,Medium,1.0,Yes,Yes,Messenger,Green,17.749338,86.02312
...,...,...,...,...,...,...,...,...,...,...,...
299995,299995,Adidas,Leather,Small,9.0,No,No,Tote,Blue,12.730812,129.99749
299996,299996,Jansport,Leather,Large,6.0,No,Yes,Tote,Blue,26.633182,19.85819
299997,299997,Puma,Canvas,Large,9.0,Yes,Yes,Backpack,Pink,11.898250,111.41364
299998,299998,Adidas,Nylon,Small,1.0,No,Yes,Tote,Pink,6.175738,115.89080
299999,299999,Under Armour,Canvas,Small,2.0,No,Yes,Backpack,Black,18.568865,26.72762

In [6]:
df2 = pd.read_csv('training_extra.csv', sep=',')
df2

,id,Brand,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg),Price
0,500000,Under Armour,Canvas,Small,10.0,Yes,Yes,Tote,Blue,23.882052,114.11068
1,500001,Puma,Polyester,Small,4.0,No,Yes,Backpack,Green,11.869095,129.74972
2,500002,Jansport,Polyester,Small,8.0,Yes,Yes,Tote,Red,8.092302,21.37370
3,500003,Nike,Nylon,Large,7.0,No,No,Messenger,Pink,7.719581,48.09209
4,500004,Nike,Leather,Large,9.0,No,Yes,Tote,Green,22.741826,77.32461
...,...,...,...,...,...,...,...,...,...,...,...
3694313,4194313,Nike,Canvas,NaN,3.0,Yes,Yes,Messenger,Blue,28.098120,104.74460
3694314,4194314,Puma,Leather,Small,10.0,Yes,Yes,Tote,Blue,17.379531,122.39043
3694315,4194315,Jansport,Canvas,Large,10.0,No,No,Backpack,Red,17.037708,148.18470
3694316,4194316,Puma,Canvas,NaN,2.0,No,No,Backpack,Gray,28.783339,22.32269
3694317,4194317,Under Armour,Polyester,Medium,2.0,Yes,No,Backpack,Blue,23.076169,107.61199

In [103]:
df_test2 = pd.read_csv('test.csv', sep = ',')
df_test2

,id,Brand,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg)
0,300000,Puma,Leather,Small,2.0,No,No,Tote,Green,20.671147
1,300001,Nike,Canvas,Medium,7.0,No,Yes,Backpack,Green,13.564105
2,300002,Adidas,Canvas,Large,9.0,No,Yes,Messenger,Blue,11.809799
3,300003,Adidas,Nylon,Large,1.0,Yes,No,Messenger,Green,18.477036
4,300004,NaN,Nylon,Large,2.0,Yes,Yes,Tote,Black,9.907953
...,...,...,...,...,...,...,...,...,...,...
199995,499995,Adidas,Canvas,Large,2.0,Yes,No,Messenger,Red,7.383498
199996,499996,Nike,Polyester,Small,9.0,No,Yes,Messenger,Pink,6.058394
199997,499997,Jansport,Nylon,Small,9.0,No,Yes,Tote,Green,26.890163
199998,499998,Puma,Nylon,Large,10.0,Yes,No,Tote,Gray,25.769153
199999,499999,Under Armour,Leather,Medium,8.0,Yes,Yes,Messenger,Pink,29.175026

In [104]:
# id saved separately, will be required later
ids = df_test2['id']

In [8]:
cols = list(df.columns)
cols

['id',
 'Brand',
 'Material',
 'Size',
 'Compartments',
 'Laptop Compartment',
 'Waterproof',
 'Style',
 'Color',
 'Weight Capacity (kg)',
 'Price']

plt.figure()
plt.boxplot(df.Price)

plt.show()

In [9]:
brands = set(df.Brand.values)
for b in brands:
    print(b, df[df.Brand == b].Price.describe())
#brand show no impact on the price

Under Armour count    59992.000000
mean        81.976311
std         38.955756
min         15.000000
25%         48.131902
50%         81.995740
75%        115.791960
max        150.000000
Name: Price, dtype: float64
Adidas count    60077.000000
mean        80.631060
std         38.805601
min         15.000000
25%         46.792120
50%         80.095020
75%        113.641860
max        150.000000
Name: Price, dtype: float64
nan count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: Price, dtype: float64
Nike count    57336.000000
mean        81.319209
std         39.129019
min         15.000000
25%         47.038750
50%         80.679460
75%        114.921567
max        150.000000
Name: Price, dtype: float64
Puma count    56814.000000
mean        81.448607
std         39.229770
min         15.000000
25%         47.286623
50%         80.657200
75%        115.481230
max        150.000000
Name: Price, dtype: float64
Jansport count    56076.000000
mean        81.791276
std         38.970598
min         15.000000
25%         48.065168
50%         81.470390
75%        115.461358
max        150.000000
Name: Price, dtype: float64

In [10]:
ohe = OneHotEncoder(sparse_output=False)
ohe

OneHotEncoder(sparse_output=False)

In [11]:
std_scaler = StandardScaler()
std_scaler

StandardScaler()

In [12]:
numerical = []
categorical = []
for c in cols:
    if df[c].dtype == 'float64':
        numerical.append(c)
    else:
        categorical.append(c)
numerical.pop()
categorical.remove('id')
print(numerical)
print(categorical)
#distribute features into numerical and categorical

['Compartments', 'Weight Capacity (kg)']
['Brand', 'Material', 'Size', 'Laptop Compartment', 'Waterproof', 'Style', 'Color']

In [13]:
df_normalized = pd.DataFrame()

In [14]:
ohe.fit(df[categorical])
ohe_cats = ohe.transform(df[categorical])
ohe_cats

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
ohe.get_feature_names_out()

array(['Brand_Adidas', 'Brand_Jansport', 'Brand_Nike', 'Brand_Puma',
       'Brand_Under Armour', 'Brand_nan', 'Material_Canvas',
       'Material_Leather', 'Material_Nylon', 'Material_Polyester',
       'Material_nan', 'Size_Large', 'Size_Medium', 'Size_Small',
       'Size_nan', 'Laptop Compartment_No', 'Laptop Compartment_Yes',
       'Laptop Compartment_nan', 'Waterproof_No', 'Waterproof_Yes',
       'Waterproof_nan', 'Style_Backpack', 'Style_Messenger',
       'Style_Tote', 'Style_nan', 'Color_Black', 'Color_Blue',
       'Color_Gray', 'Color_Green', 'Color_Pink', 'Color_Red',
       'Color_nan'], dtype=object)

In [16]:
df_normalized[ohe.get_feature_names_out()]=ohe_cats
df_normalized

,Brand_Adidas,Brand_Jansport,Brand_Nike,Brand_Puma,Brand_Under Armour,Brand_nan,Material_Canvas,Material_Leather,Material_Nylon,Material_Polyester,...,Style_Messenger,Style_Tote,Style_nan,Color_Black,Color_Blue,Color_Gray,Color_Green,Color_Pink,Color_Red,Color_nan
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
299996,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
299997,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
299998,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
299999,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
std_scaler.fit(df[numerical])

StandardScaler()

In [18]:
std_scaled = std_scaler.transform(df[numerical])
std_scaled

array([[ 0.53840844, -0.92125175],
       [ 1.57619753,  1.2987899 ],
       [-1.19124004, -0.19897422],
       ...,
       [ 1.23026783, -0.88012488],
       [-1.53716974, -1.70151025],
       [-1.19124004,  0.07734728]])

In [19]:
df_normalized[numerical] = std_scaled
df_normalized

,Brand_Adidas,Brand_Jansport,Brand_Nike,Brand_Puma,Brand_Under Armour,Brand_nan,Material_Canvas,Material_Leather,Material_Nylon,Material_Polyester,...,Style_nan,Color_Black,Color_Blue,Color_Gray,Color_Green,Color_Pink,Color_Red,Color_nan,Compartments,Weight Capacity (kg)
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.538408,-0.921252
1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.576198,1.298790
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.191240,-0.198974
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.884338,-0.730995
4,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-1.537170,-0.040284
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.230268,-0.760622
299996,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.192479,1.234866
299997,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.230268,-0.880125
299998,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.537170,-1.701510
299999,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.191240,0.077347

In [20]:
df_normalized['Price'] = df['Price']
df_normalized
#complete df after data preparation

,Brand_Adidas,Brand_Jansport,Brand_Nike,Brand_Puma,Brand_Under Armour,Brand_nan,Material_Canvas,Material_Leather,Material_Nylon,Material_Polyester,...,Color_Black,Color_Blue,Color_Gray,Color_Green,Color_Pink,Color_Red,Color_nan,Compartments,Weight Capacity (kg),Price
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.538408,-0.921252,112.15875
1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.576198,1.298790,68.88056
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.191240,-0.198974,39.17320
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.884338,-0.730995,80.60793
4,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-1.537170,-0.040284,86.02312
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.230268,-0.760622,129.99749
299996,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.192479,1.234866,19.85819
299997,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.230268,-0.880125,111.41364
299998,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.537170,-1.701510,115.89080
299999,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.191240,0.077347,26.72762

In [21]:
df_normalized.describe()

,Brand_Adidas,Brand_Jansport,Brand_Nike,Brand_Puma,Brand_Under Armour,Brand_nan,Material_Canvas,Material_Leather,Material_Nylon,Material_Polyester,...,Color_Black,Color_Blue,Color_Gray,Color_Green,Color_Pink,Color_Red,Color_nan,Compartments,Weight Capacity (kg),Price
count,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,...,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,3.000000e+05,2.998620e+05,300000.000000
mean,0.200257,0.186920,0.191120,0.189380,0.199973,0.032350,0.226680,0.244720,0.235343,0.265433,...,0.154593,0.160323,0.167600,0.154620,0.172300,0.157397,0.033167,-1.243450e-16,-3.384214e-16,81.411107
std,0.400193,0.389848,0.393184,0.391811,0.399981,0.176928,0.418685,0.429922,0.424214,0.441564,...,0.361517,0.366906,0.373511,0.361543,0.377642,0.364175,0.179072,1.000002e+00,1.000002e+00,39.039340
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.537170e+00,-1.870271e+00,15.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-8.453103e-01,-8.514727e-01,47.384620
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.534510e-01,5.543300e-03,80.956120
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.843381e-01,8.572506e-01,115.018160
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.576198e+00,1.718125e+00,150.000000

In [22]:
df_prep = df_normalized.dropna()
df_prep

,Brand_Adidas,Brand_Jansport,Brand_Nike,Brand_Puma,Brand_Under Armour,Brand_nan,Material_Canvas,Material_Leather,Material_Nylon,Material_Polyester,...,Color_Black,Color_Blue,Color_Gray,Color_Green,Color_Pink,Color_Red,Color_nan,Compartments,Weight Capacity (kg),Price
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.538408,-0.921252,112.15875
1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.576198,1.298790,68.88056
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.191240,-0.198974,39.17320
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.884338,-0.730995,80.60793
4,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-1.537170,-0.040284,86.02312
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.230268,-0.760622,129.99749
299996,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.192479,1.234866,19.85819
299997,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.230268,-0.880125,111.41364
299998,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.537170,-1.701510,115.89080
299999,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.191240,0.077347,26.72762

In [23]:
#trying linear regression model
lr = LinearRegression()
lr

LinearRegression()

In [24]:
train, test = train_test_split(df_prep, test_size = 0.2, random_state=42)
train.head()

,Brand_Adidas,Brand_Jansport,Brand_Nike,Brand_Puma,Brand_Under Armour,Brand_nan,Material_Canvas,Material_Leather,Material_Nylon,Material_Polyester,...,Color_Black,Color_Blue,Color_Gray,Color_Green,Color_Pink,Color_Red,Color_nan,Compartments,Weight Capacity (kg),Price
202913,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-0.845310,-0.315877,21.01494
27215,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.230268,0.147010,61.15716
220789,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.576198,-1.487938,54.66424
220433,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-0.153451,1.412655,46.55220
267936,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.538408,0.695400,24.21613

In [25]:
lr.fit(train.drop('Price', axis = 1), train[['Price']])

LinearRegression()

In [26]:
# first model result, quite unsatisfying
pred = lr.predict(test.drop('Price', axis = 1))
print(mean_squared_error(test[['Price']], pred))
print(pred)

1517.0585955787844
[[81.578125  ]
 [85.01953125]
 [82.4609375 ]
 ...
 [81.66015625]
 [77.03515625]
 [83.02734375]]

In [48]:
#drop na for train dataset
df_normalized[numerical] = df[numerical]
df_normalized = df_normalized.dropna()
df_normalized.isna().sum()

Brand_Adidas              0
Brand_Jansport            0
Brand_Nike                0
Brand_Puma                0
Brand_Under Armour        0
Brand_nan                 0
Material_Canvas           0
Material_Leather          0
Material_Nylon            0
Material_Polyester        0
Material_nan              0
Size_Large                0
Size_Medium               0
Size_Small                0
Size_nan                  0
Laptop Compartment_No     0
Laptop Compartment_Yes    0
Laptop Compartment_nan    0
Waterproof_No             0
Waterproof_Yes            0
Waterproof_nan            0
Style_Backpack            0
Style_Messenger           0
Style_Tote                0
Style_nan                 0
Color_Black               0
Color_Blue                0
Color_Gray                0
Color_Green               0
Color_Pink                0
Color_Red                 0
Color_nan                 0
Compartments              0
Weight Capacity (kg)      0
Price                     0
dtype: int64

In [49]:
# initiating x and y for train cols
x = df_normalized.drop(columns = ['Price'], axis = 1)
y = df_normalized['Price']
x.head()

,Brand_Adidas,Brand_Jansport,Brand_Nike,Brand_Puma,Brand_Under Armour,Brand_nan,Material_Canvas,Material_Leather,Material_Nylon,Material_Polyester,...,Style_nan,Color_Black,Color_Blue,Color_Gray,Color_Green,Color_Pink,Color_Red,Color_nan,Compartments,Weight Capacity (kg)
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,11.611723
1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,10.0,27.078537
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,16.643760
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,8.0,12.937220
4,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,17.749338

In [50]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
x_train.head()

,Brand_Adidas,Brand_Jansport,Brand_Nike,Brand_Puma,Brand_Under Armour,Brand_nan,Material_Canvas,Material_Leather,Material_Nylon,Material_Polyester,...,Style_nan,Color_Black,Color_Blue,Color_Gray,Color_Green,Color_Pink,Color_Red,Color_nan,Compartments,Weight Capacity (kg)
241791,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,9.0,22.898388
89954,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,9.0,19.890983
221735,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,29.275628
129613,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,5.0,25.619550
238914,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,17.584095

In [52]:
#initiating model
model = ElasticNet(random_state = 42)
model

ElasticNet(random_state=42)

In [53]:
#params of the model
model.get_params()

{'alpha': 1.0,
 'copy_X': True,
 'fit_intercept': True,
 'l1_ratio': 0.5,
 'max_iter': 1000,
 'positive': False,
 'precompute': False,
 'random_state': 42,
 'selection': 'cyclic',
 'tol': 0.0001,
 'warm_start': False}

In [54]:
#train model resuls
model.fit(x_train, y_train)
model.score(x_train, y_train)

0.00032581601155623474

In [58]:
#train model result
pred = model.predict(x_test)
print(mean_absolute_error(y_test, pred))

33.778277073893044

In [60]:
#train model results
mse = mean_squared_error(y_test, pred)
rmse = np.sqrt(mse)
rmse

38.99467605046221

In [77]:
#dropping id, appending it later
df_test = df_test.drop(columns = ['id'])
df_test.head()

,Compartments,Weight Capacity (kg),Brand_Adidas,Brand_Jansport,Brand_Nike,Brand_Puma,Brand_Under Armour,Brand_nan,Material_Canvas,Material_Leather,...,Style_Messenger,Style_Tote,Style_nan,Color_Black,Color_Blue,Color_Gray,Color_Green,Color_Pink,Color_Red,Color_nan
0,2.0,20.671147,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,7.0,13.564105,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,9.0,11.809799,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,1.0,18.477036,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,2.0,9.907953,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [86]:
#fixing cols order
cols = ['Brand_Adidas',
 'Brand_Jansport',
 'Brand_Nike',
 'Brand_Puma',
 'Brand_Under Armour',
 'Brand_nan',
 'Material_Canvas',
 'Material_Leather',
 'Material_Nylon',
 'Material_Polyester',
 'Material_nan',
 'Size_Large',
 'Size_Medium',
 'Size_Small',
 'Size_nan',
 'Laptop Compartment_No',
 'Laptop Compartment_Yes',
 'Laptop Compartment_nan',
 'Waterproof_No',
 'Waterproof_Yes',
 'Waterproof_nan',
 'Style_Backpack',
 'Style_Messenger',
 'Style_Tote',
 'Style_nan',
 'Color_Black',
 'Color_Blue',
 'Color_Gray',
 'Color_Green',
 'Color_Pink',
 'Color_Red',
 'Color_nan','Compartments',
 'Weight Capacity (kg)']
df_test = df_test[cols]
df_test.head()

,Brand_Adidas,Brand_Jansport,Brand_Nike,Brand_Puma,Brand_Under Armour,Brand_nan,Material_Canvas,Material_Leather,Material_Nylon,Material_Polyester,...,Style_nan,Color_Black,Color_Blue,Color_Gray,Color_Green,Color_Pink,Color_Red,Color_nan,Compartments,Weight Capacity (kg)
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,20.671147
1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,7.0,13.564105
2,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,9.0,11.809799
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,18.477036
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,9.907953

In [95]:
#replacing na with mean
df_test['Weight Capacity (kg)'].fillna(df_test['Weight Capacity (kg)'].mean(), inplace=True)

In [97]:
#check for pending NANs
df_test.isna().sum()

Brand_Adidas              0
Brand_Jansport            0
Brand_Nike                0
Brand_Puma                0
Brand_Under Armour        0
Brand_nan                 0
Material_Canvas           0
Material_Leather          0
Material_Nylon            0
Material_Polyester        0
Material_nan              0
Size_Large                0
Size_Medium               0
Size_Small                0
Size_nan                  0
Laptop Compartment_No     0
Laptop Compartment_Yes    0
Laptop Compartment_nan    0
Waterproof_No             0
Waterproof_Yes            0
Waterproof_nan            0
Style_Backpack            0
Style_Messenger           0
Style_Tote                0
Style_nan                 0
Color_Black               0
Color_Blue                0
Color_Gray                0
Color_Green               0
Color_Pink                0
Color_Red                 0
Color_nan                 0
Compartments              0
Weight Capacity (kg)      0
dtype: int64

In [98]:
#importing predict to the test dataset
pred = model.predict(df_test)
df_test['Price'] = pred
df_test.head()

,Brand_Adidas,Brand_Jansport,Brand_Nike,Brand_Puma,Brand_Under Armour,Brand_nan,Material_Canvas,Material_Leather,Material_Nylon,Material_Polyester,...,Color_Black,Color_Blue,Color_Gray,Color_Green,Color_Pink,Color_Red,Color_nan,Compartments,Weight Capacity (kg),Price
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,20.671147,81.723104
1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,7.0,13.564105,81.079892
2,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,9.0,11.809799,80.921122
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,18.477036,81.524529
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,9.907953,80.748998

In [105]:
#appendig previously deleted id col, required for result output
df_test['id'] = ids
df_test.head()

,Brand_Adidas,Brand_Jansport,Brand_Nike,Brand_Puma,Brand_Under Armour,Brand_nan,Material_Canvas,Material_Leather,Material_Nylon,Material_Polyester,...,Color_Blue,Color_Gray,Color_Green,Color_Pink,Color_Red,Color_nan,Compartments,Weight Capacity (kg),Price,id
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,2.0,20.671147,81.723104,300000
1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,7.0,13.564105,81.079892,300001
2,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,9.0,11.809799,80.921122,300002
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,18.477036,81.524529,300003
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,9.907953,80.748998,300004

In [106]:
#export result
result = df_test.to_csv('result.csv', columns = ['id', 'Price'])